### PR TITLE
ui[fix] :: added exit if fails to delete folder to indicate end user

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
@maximilianhuber Please review the PR. and merge if the changes are ok for you.

### CODE REVIEW

**Comment by maximilianhuber** [comment]
The `upload=-1` does not always cause the error:

tmp

It is also very rigorous to remove all negative values from this function. I think we should find a better place to solve this issue without these far reaching implications.

**Comment by shaheemazmalmmd** [comment]
May Be yes. But  is there any other place where we are using Negative values in url ??.  but i sisnt found any when i searched.

**Comment by maximilianhuber** [comment]
such a restriction in a central position introduces a high risk for bugs. And I don't think that one can test every possible request of every agent to check, that none of them will try to use GET for an negative value. You should try to find the place where the `-1` is set.

Btw.: this still does not explain, why the example above is working. I thought that every `upload=-1` leads to the error.

**Comment by shaheemazmalmmd** [comment]
Yes you are right!! lets try to fix this from some other place. 

i'm also confused with this behavior if a job gets failed then only it gets crashes it seems. and that too it effects all the uploads get uploaded after the crashed job. geeky scan is not shown for them.

**Comment by shaheemazmalmmd** [comment]
There are come checks for upload < 0 in the code if -1 is removed the it may not work. so i was thinking to remove upload from url of geeky scan because upload parameter is not used while showing geeky scan.

**Comment by maximilianhuber** [comment]
If this is a pure geeky-scan-problem it might might be a good idea to put its solution into another PR to fossology/fossology.

**Comment by shaheemazmalmmd** [comment]
Sure, But What about this PR ??

**Comment by shaheemazmalmmd** [comment]
observed that keeping printf and killing scheduler(exit -1) is crashing the application. may be use info

**Pull request closed without merging**
