### PR TITLE
fix(delagent): user permissions dominate other permissions

### PR DESCRIPTION
**Pull request by maximilianhuber**
@shaheemazmalmmd: This is a **first draft** of a solution for the problem mentioned in the [comment](https://github.com/fossology/fossology/pull/602#issuecomment-170891250). Maybe you could have a look at it.

### CODE REVIEW

**Comment by maximilianhuber** [comment]
This also fixes the problem with `delagent -u`. It now lists exactly the readable uploads.

BUT: it now iterates over all uploads and checks the permissions for everyone. That might be slow compared to a pure DB solution.

**Comment by maximilianhuber** [comment]
The permissions of a user are computed as follows:

get the user permission level as `user_perm`
- **if user is admin**
   - return `ADMIN_PERM`
- **else** get permissions granted to the group (`group_perm`) of an user and get the public permissions (`public_perm`)
   - return `min(user_perm, max(group_perm, public_perm))`

**Comment by maximilianhuber** [comment]
@shaheemazmalmmd: have you found the time to have a look at this PR?

**Comment by shaheemazmalmmd** [comment]
yes, the code looks fine.

**Comment by maximilianhuber** [comment]
Ok, then I will merge it and one of us should test whether there is something missing/wrong.

**Pull request merged**
